import{a as b,S as L,i as w}from"./assets/vendor-483db976.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&r(d)}).observe(document,{childList:!0,subtree:!0});function i(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=i(t);fetch(t.href,s)}})();const v="42651463-7e9bc4d6a898bed570bd4622e",C="https://pixabay.com/api/",f=document.querySelector(".loader");let S=15;async function m(o,e){const i=new URLSearchParams({key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:S});f.style.display="block";try{const r=await b.get(`${C}?${i}`);if(!r===200)throw new Error("Network response was not OK");const t=r.data;return f.style.display="none",t}catch(r){throw console.error(r),r}}function u(o){return o.hits.map(e=>`<div class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <div class="gallery-image-info">
          <p class="image-info-item"><span class="items-text">Likes: </span>${e.likes}</p>
          <p class="image-info-item"><span class="items-text">Views: </span>${e.views}</p>
          <p class="image-info-item"><span class="items-text">Comments: </span>${e.comments}</p>
          <p class="image-info-item"><span class="items-text">Downloads: </span>${e.downloads}</p>
      </div>
  </div>`).join("")}const g=document.querySelector(".search-form"),n=document.querySelector(".gallery"),l=document.querySelector(".load-btn");let p="",a,c;l.style.display="none";const h=new L(".gallery-link",{captions:!0,captionsData:"alt",captionDelay:200});g.addEventListener("submit",$);l.addEventListener("click",k);function $(o){o.preventDefault(),n.innerHTML="",a=1,p=g.elements.searchQuery.value.trim(),m(p,a).then(e=>{c=e.totalHits;const i=u(e);n.insertAdjacentHTML("beforeend",i),h.refresh(),y(e)}).catch(e=>console.log(e))}function k(){a++,m(p,a).then(o=>{c=o.totalHits;const e=u(o);n.insertAdjacentHTML("beforeend",e),h.refresh(),y(o)}).catch(o=>console.log(o))}function y(o){n.children.length<c?l.style.display="block":a*15>=c?(l.style.display="none",w.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#4CAF50",messageColor:"#fff",titleColor:"#fff",progressBarColor:"#4CAF50",position:"topRight"})):u(o)}function x(){const o=n.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:2*o,behavior:"smooth"})}n.addEventListener("scroll",x);
//# sourceMappingURL=commonHelpers.js.map
