import{a as L,i as m,S as w}from"./assets/vendor-483db976.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const v="42651463-7e9bc4d6a898bed570bd4622e",C="https://pixabay.com/api/",f=document.querySelector(".loader");let S=15;async function g(o,e){const i=new URLSearchParams({key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:S});f.style.display="block";try{const s=await L.get(`${C}?${i}`);if(!s===200)throw new Error("Network response was not OK");const t=s.data;return f.style.display="none",t.hits.length===0&&m.error({title:"Error",fontSize:"large",close:!1,position:"topRight",messageColor:"white",timeout:2e3,backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),t}catch(s){throw console.error(s),s}}function p(o){return o.hits.map(e=>`<div class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <div class="gallery-image-info">
          <p class="image-info-item"><span class="items-text">Likes: </span>${e.likes}</p>
          <p class="image-info-item"><span class="items-text">Views: </span>${e.views}</p>
          <p class="image-info-item"><span class="items-text">Comments: </span>${e.comments}</p>
          <p class="image-info-item"><span class="items-text">Downloads: </span>${e.downloads}</p>
      </div>
  </div>`).join("")}const h=document.querySelector(".search-form"),n=document.querySelector(".gallery"),l=document.querySelector(".load-btn");let u="",a,c;l.style.display="none";const y=new w(".gallery-link",{captions:!0,captionsData:"alt",captionDelay:200});h.addEventListener("submit",k);l.addEventListener("click",P);function k(o){o.preventDefault(),n.innerHTML="",a=1,u=h.elements.searchQuery.value.trim(),g(u,a).then(e=>{c=e.totalHits;const i=p(e);n.insertAdjacentHTML("beforeend",i),y.refresh(),b(e)}).catch(e=>console.log(e))}function P(){a++,g(u,a).then(o=>{c=o.totalHits;const e=p(o);n.insertAdjacentHTML("beforeend",e),y.refresh(),b(o)}).catch(o=>console.log(o))}function b(o){n.children.length<c?l.style.display="block":a*15>=c?(l.style.display="none",m.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#4CAF50",messageColor:"#fff",titleColor:"#fff",progressBarColor:"#4CAF50",position:"topRight"})):p(o)}function $(){const o=n.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:2*o,behavior:"smooth"})}n.addEventListener("scroll",$);
//# sourceMappingURL=commonHelpers.js.map
